### ISSUE TITLE
unable to import plaintext andOTP json file

### ISSUE THREAD

**Issue by magiruuvelvet** [paolostivanin/OTPClient#103]
is there no support to import plaintext andOTP json files? i generated an andOTP compatible json using a custom-made script from Authy (copied files from my rooted device). the file can be imported in andOTP just fine and all tokens work, but OTPClient just prompts me for password and gives me an error no matter if the password is empty or some random string.

i have over 100 tokens and i don't want to manually enter everything in the application. please help

PS: i know i technically could export an encrypted file in andOTP and transfer over the file and use that, but this seems like a missing feature which should be supported

**Comment by paolostivanin** [comment]
Hi,
Yes, you're right. Currently, there is no support for plain text files.

It's not really a good idea to move around plain text files with such sensitive information, that's why I've never implemented such feature (I don't want to encourage this behaviour). 

Of course, if a lot of people will ask for plain text support than I'll add it :) but, at the moment, I have no plan for it.

**Comment by magiruuvelvet** [comment]
ok thanks for the info, than I will re-export the tokens in encrypted state once I have to motivation to do so
