### ISSUE TITLE
Switch to Meson build system

### ISSUE THREAD

**Issue by paolostivanin** [paolostivanin/OTPClient#107]
1. would it make sense to switch from CMake to Meson (https://mesonbuild.com)?
2. what are the pros and cons about both build system?
3. which build system has better IDE integration?

**Comment by paolostivanin** [comment]
I've done some research and I've played a bit with it. I really like meson and I find it way more powerful, easier and intuitive than cmake.
But some of the things I need are present only in recent versions, meaning that I'd have to hack around to solve problem for old distros (eg Ubuntu 16.04 or 18.04, Debian stable, etc).
As I don't see the need to immediately switch to meson, I won't spend any more time on this until `v3.0` where GTK4 will be used and, therefore, only recent distros will be supported.

**Comment by FranciscoPombal** [comment]
@paolostivanin 

> I've done some research and I've played a bit with it. I really like meson and I find it way more powerful, easier and intuitive than cmake.

I disagree with the change to Meson.

- You might be finding Meson "way more powerful, easier and intuitive than cmake" because you're not using "modern CMake" features and best practices right now. For example, you're manually setting the `CMAKE_C_FLAGS` variable, not making use of `target_include_directories`, and other small things, from a cursory look at the CML.txt.
- You're already using CMake, which is overall more widely used in the C/C++ ecosystem, and your project is not that complex, so improving the current CMake script is the least costly change IMO.
- Switching to Meson introduces a build-time dependency on Python 3 (this might not be that big of a deal, tbh), whereas CMake can bootstrap itself with a standard C++ toolchain, and there are many ways of installing official pre-built binaries, including an official APT repository: https://apt.kitware.com/

But hey, it's your project, so it's your call. Plus I don't have any real stake in it right now. I might find time to post a PR with some suggested improvements to the CML.txt in the future.

Here are some resources I personally recommend if you want to get up to speed with CMake:
- https://crascit.com/professional-cmake/ ($30, but by far the best resource out there, very well written and structured; disclaimer: I'm not affiliated with the author in any way, this is an honest opinion)
- https://cliutils.gitlab.io/modern-cmake/
- https://www.youtube.com/watch?v=y7ndUhdQuU8
- https://www.youtube.com/watch?v=y9kSr5enrSk
- https://www.youtube.com/watch?v=eC9-iRN2b04
- https://www.youtube.com/watch?v=bsXLMQ6WgIk
- https://www.youtube.com/playlist?list=PLK6MXr8gasrGmIiSuVQXpfFuE1uPT615s
- https://cgold.readthedocs.io/en/latest/ (WIP)

I find that the CMake documentation is excellent _reference_ documentation, not so much for tutorials/concrete real-world examples, but it has been improving in that regard as well.

And here is a (slightly inflammatory, IMO) article arguing in favor of CMake: https://www.rojtberg.net/1481/do-not-use-meson/

**Comment by paolostivanin** [comment]
Thanks for your suggestions, really appreciated. I'll put those links on my "to-do" list :)

TBH, I didn't invest much time on learning CMake and Meson. As my free time is very limited, I tend to focus on development. So building/packaging/etc comes with a very low priority.

**Comment by paolostivanin** [comment]
will stay with CMake
