### ISSUE TITLE
Please add donation bitcoin/monero address.

### ISSUE THREAD

**Issue by brainscar** [paolostivanin/OTPClient#111]
Would like to donate.

**Comment by paolostivanin** [comment]
Hello,
while I really appreciate your thought, I **don't** take donation for my project :smile: (but thank you messages are always well welcomed :) )
I work on it on my free time (when I can) and, if I'd start taking donation, it'd seem more like a job than a side project.
With that I'm **not** saying that OTPClient is a toy project or something I'm doing just because I have some spare time.
This is a regular, well maintained, well developed and well thought project. I've spent, I spend and will spend a lot of hours thinking what's the best way to achieve something or how I can improve existing features. For example, I set up a CI so I can check that it compiles on all major distro, I run Coverity scan with every release, etc. :smile: 

So, if you wanna donate something just donate a minute of your time to share this project with all the people you know :+1: 

Thank you again,

Paolo
