### ISSUE TITLE
Client opens without asking for a password

### ISSUE THREAD

**Issue by manero6** [paolostivanin/OTPClient#274]
Hi, first of all thanks a lot for this great app :)

I'm using 2.6.3 from Flathub on Fedora 36.
This version unlock itself on opening without asking for a password.

Saluti

**Comment by paolostivanin** [comment]
Since you're not the first to ask for that, I've created a pinned issue :) 

https://github.com/paolostivanin/OTPClient/issues/275

Quick question: when you upgraded to/installed v2.6.x, didn't you see a status bar (just below the titlebar) showing a message about this feature? It should have appeared :thinking:

**Comment by manero6** [comment]
I can't say exactly when I updated it, as I update my system almost daily.
I know for sure that I didn't use the client for ~3 weeks, maybe even more.
Also the last time I used it, it definitely asked for a pass.

Today by opening it I did not see any status bar.
