### ISSUE TITLE
Can't create a new database if open failed on first launch

### ISSUE THREAD

**Issue by arokettu** [paolostivanin/OTPClient#303]
1) Launch the app on the blank system
2) Choose to restore existing - failed, corrupted database or forgot password or whatever
3) Endless cycle of choosing either to close the app or to select a file until I either remove the selected database file or the app config

**Comment by paolostivanin** [comment]
Thanks for reporting this. I'll have a look at it after vacation 😊

**Comment by Rtizer-9** [comment]
I'm having the exact same issue and I encountered a few others which happens in conjunction with this issue:

I had to reinstall the whole os so I exported encrypted backup and while restoring it said "either the password is incorrect or db is corrupted".

I then exported backups from my mobile aegis thinking that maybe the desktop bkp is really corrupted or there's a single letter issue in password although I exactly remember the password.....and same issue happened again.

I then looked at my aegis setting and it has biometric lock turned on so I thought maybe an export generated like this might be a bit different from only encrypted ones.

I then again exported all kinds of tokens like encrypted, unencrypted json and plain text after setting a different password for the exports and backups.... again same issue....yeah otpclient even asked me password for unencrypted and plain text files literally.

I then looked at both flatpak and deb version and when I finally deleted the import path from the config file of deb version, it started behaving normally and I was able to import the first encrypted json from the app itself without any issue.

So the issue is not just that it gets stuck on the first file itself if you select it on first launch and also does not let you create another new database as mentioned by OP but it's giving that "corrupt or pswd wrong" error for even unencrypted and plain text files.

**Comment by paolostivanin** [comment]
Thank you for the detailed report. I'll fix it this (hopefully) this week :smile:

**Comment by paolostivanin** [comment]
@arokettu @Rtizer-9 can you please tell me what version are you using? thanks

**Comment by Rtizer-9** [comment]
3.1.9

**Comment by arokettu** [comment]
> 3.1.9

Same
