### ISSUE TITLE
OTPClient generates invalid code

### ISSUE THREAD

**Issue by katonagl** [paolostivanin/OTPClient#325]
I have OTPClient configured for outlook.office.com and also for a university system. For both systems OTPClient worked for a few days, but now after a system update  the generated code is invalid. Trying the same secret in another TOTP generator (keysmith) on the same computer produces valid code. Recreating the entries in OTPClient or requesting new secrets does not help. OTPClient is 3.2.1 under openSUSE Tumbleweed. With the current update libcotp2 was updated to 2.1.0 from 2.0.2.

**Comment by paolostivanin** [comment]
Hello,
That's because OTPClient needs to be recompiled against the newer libcotp.

Are you using it from my repo (it's for Leap and Fedora)? 

https://build.opensuse.org/project/show/home:polslinux:otpclient

On tumbleweed I have submitted the rebuild yesterday because it wasn't done automatically, so it might take a couple of days.
