### ISSUE TITLE
[Feature Request] Able to group tokens

### ISSUE THREAD

**Issue by partha51613** [paolostivanin/OTPClient#346]
Hello everyone,

While using the app, there can be too many TOTP and it is difficult to quickly pickup the one I need. So grouping TOTPs can be of big help.

For eg: All social media tokens (FB, Instagram, Twitter etc) can be in the group SOCIALMEDIA.

**Comment by paolostivanin** [comment]
Thanks for reporting this, I'll think about it!

**Comment by paolostivanin** [comment]
I've thought about it. With v4 there will be a new full search function, so searching for tokens will be a seamless (and useful) experience. Grouping tokens would mean change again completely the UI, and this won't happen since I've already done most of the basic work for v4. 
But I think the new search will be more than enough for everyone :smile:
