### ISSUE TITLE
UI feedback

### ISSUE THREAD

**Issue by dw** [paolostivanin/OTPClient#359]
Hey there,

I've been a heavy user of otpclient for years and mostly love it. There are a couple of issues with the UI I'd love to see corrected, and would be happy to volunteer a bit of time for each (or all!) of them if there was interest in accepting any of the contributions upstream:

- Search unreliability. CTRL+F "github" never does what I want, regardless of which search field is selected in the preferences. Ideally search should be over any field without having to worry about a setting, and should work reliably (I have not looked at the code to understand what is going on). It seems the unreliability might be related to not doing substring search, or struggling with account names containing spaces

- Toggle delete rows modality - not sure if it was a conscious choice to give the UI a whole major mode just for deleting items. Would this not be better present on a right-click context menu? After a few years of use, I am still right-clicking each time, and on remembering how it's supposed to work, am genuinely afraid of the delete button because it changes how the UI works when enabled. Even with the delete button in the toolbar, the expectation would be that the currently selected item is deleted, whereas (without verifying - again, slightly scared of that button :P) the current behaviour is that any item selected after clicking the button is deleted

- Toggle row reordering - another mode. Could it not be enabled by default?

- Clicking column titles to sort-by-column. I have 2 pages of TOTP entries and manual sorting is never desirable

- Edit row hidden on the hamburger menu. Would love to see this moved to a context menu too, because that's also an orthodox location for a per-item action

- Add from QR code: this menu sees frequent use, but it is buried in a submenu. Could these 2 menu items be brought up one level to save a click (and slightly improve discoverability especially when sleepy)

-  Clicking to show a TOTP which is just about to expire requires a second click. Would probably be better to show the code for a fixed number of seconds, rather than up until the next expiry point. This one interrupts me almost every week

Apologies for the unsolicited feedback. I still love the app, and suspect there may be some logic behind not hiding stuff in a context menu

**Comment by paolostivanin** [comment]
Hello,
thanks a lot for taking the time to write such detailed feedback, really appreciated :smile: 
Let's go point by point:
* I know, search is completely useless in v3. I'm working on v4 which will be written from scratch and will have a useful and working search mode
* no particular reason. I did it that way lots of years ago and since I don't use the deletion feature often (maybe once a year) I've never bothered to think about how to improve it. But I agree that a context menu would be way better
* what do you mean? That rows can be reordered by default at any time? In that case, I'll have to think about it, because reordering rows is a delicate operation that requires updating the db every time it's done
* I had to remove this feature because it's broken on gtktreeview (that's why I'm moving away from this widget with v4)
* agreed about having this in the context menu
* could be, I'll have to think about it
* makes sense, I'll add this too!

**Comment by paolostivanin** [comment]
To-Do for v3.7.0:
- [ ] use context menu for row editing and deleting
- [ ] show next otp automatically if remaining time is < 8s

**Comment by paolostivanin** [comment]
Everything I could do on v3 has been done. For the more juicy part (search, reorder, etc), you've gotta wait for v4 :smile:

**Comment by paolostivanin** [comment]
I still have to test the changes I made :smile: seems like no luck in getting everything working at the first try lol

**Comment by paolostivanin** [comment]
Now everything works fine, at least for me :smile: could you please try against latest master and let me know?

Thanks
