### ISSUE TITLE
implausible suggested minimum for Secure Memory / memlock

### ISSUE THREAD

**Issue by HughR** [paolostivanin/OTPClient#384]
https://github.com/paolostivanin/OTPClient/wiki/Secure-Memory-Limitations

This page suggests:
 `memlock limit either greater than 67108864 KB`

That's an insane amount of locked physical RAM (67 GB).  Perhaps "KB" is supposed to be "B".  Even that seems excessive.

Less important comment: that number is so precise as to be unreadable -- how is it derived?

(A diagnostic told me to go look at the web page because of a known bug with the flatpak version (https://github.com/paolostivanin/OTPClient/issues/372)

**Comment by paolostivanin** [comment]
hello! Thanks for reporting this, I've fixed the wiki.

The suggestion to use at least 64 MiB is because I've seen numerous people complaining about flatpak weirdness. Unfortunately, it's not possible to calculate a minimum amount because it's not just "the size of the database".

Many distros have a memlock limit set to `unlimited` by default, which makes perfect sense for desktop usage in 2024.

**Comment by paolostivanin** [comment]
done, thanks a lot again!
