### ISSUE TITLE
Easier token add (scan/upload barcode)

### ISSUE THREAD

**Issue by nedrichards** [paolostivanin/OTPClient#60]
The token add workflow is a bit scary for newer users (lots of text boxes without much explanation). It should be possible to make a simpler capture experience - perhaps by using a laptops webcam and a QR code parsing library - or more clearly explaining how to get the information for a series of popular services.

**Comment by paolostivanin** [comment]
IMHO, reading from webcam doesn't make sense. One would need an additional laptop to read the token that will be stored into a different one. Two things can be easily implemented:
1. improve the docs, as you wrote
2. add a "import qrcode image" feature, so that the qr code can be parsed
Probably, the best option would be find a way to parse the screen, detect the image and decode it, but this it would take a loooong time to implement, because it sounds kinda complicated and I have no idea where to start :)

**Comment by nedrichards** [comment]
Well, you can print out a QR code, or hold up a phone pretty easily - parsing the screen looks like a tough gig, but an interesting one. I suppose you could connect to the 'just being written' gnome shell screencast and screenshot portals and then run a QR code detector on that. Should work pretty well actually.

**Comment by paolostivanin** [comment]
True, right. So, I looked around and it seems that the only reliable choice is the very old `zbar` lib.
I will play around with it (both drag&drop file and read from camera) and see how it goes :)

Parsing the screen is definitively something very interesting but, unfortunately, my free time is scarce for such a huge thing. I'll consider in future (for sure not before summer).

Gnome shell screencast and screenshot portals?!? I'm not aware of these...I need more info here 👀

**Comment by paolostivanin** [comment]
TODO:
* use [Zbar](http://zbar.sourceforge.net) to scan an image (drag & drop, webcam maybe later)
* add docu with examples

**Comment by paolostivanin** [comment]
3 new options will be implemented:
- scan qrcode using webcam (zbar)
- take screenshot and parse it (gnome-shell screenshot dbus api + zbar)
- manually D&D image (zbar)

**Comment by paolostivanin** [comment]
- scan: decide between simple dialog or dialog+webcam feed
- screenshot: with or without dialog (with do not show again checkbox) before taking it?
